meta_product_name: "Trippin"
meta_title: "Trippin - Making Memories, simplified"
meta_description: "Group Travelling made easy"
meta_image: "Cover.jpg" # should exist in `app/assets/images/`
meta_url: "www.start-trippin.com"
